name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.REPO_TOKEN }}

      - name: Checkout submodules
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git submodule sync --recursive
          git submodule update --init --recursive --force

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install Dalamud runtime
        uses: Blooym/setup-dalamud@v1
        with:
          branch: api15

      - name: Restore & Build
        run: |
          dotnet restore
          dotnet build -c Release -p:Platform=x64 --no-restore

      - name: Create/Update Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: api15
          files: "**/bin/x64/Release/CustomizePlus/CustomizePlus.zip"

      - name: Auto-Increment Version & Update Repo
        shell: bash
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          git clone https://x-access-token:${REPO_TOKEN}@github.com/NeXzRo/Repo.git central-repo
          python3 - <<EOF
          import json
          import os
          file_path = os.path.join("central-repo", "repo.json")
          with open(file_path, "r") as f:
              data = json.load(f)
          for entry in data:
              if entry.get("InternalName") == "CustomizePlus":
                  v = entry["AssemblyVersion"].split('.')
                  v[-1] = str(int(v[-1]) + 1)
                  new_v = ".".join(v)
                  entry["AssemblyVersion"] = new_v
          with open(file_path, "w") as f:
              json.dump(data, f, indent=2)
          EOF
          cd central-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add repo.json
          git commit -m "Auto-update CustomizePlus version"
          git push